version: 2.1

executors:
  default:
    docker:
      - image: circleci/openjdk:17.0.2
    working_directory: ~/repo

jobs:
  checkout:
    steps:
      - checkout

  build:
    steps:
      - checkout
      - run:
          name: Set permissions
          command: chmod -R 755 .
      - run:
          name: Build with Gradle
          command: ./gradlew clean build

  sonar_analysis:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner -Dsonar.java.binaries=build/classes/java \
                          -Dsonar.projectKey=Facimateintegration \
                          -Dsonar.sources=.

  package:
    steps:
      - checkout
      - run:
          name: Package Application
          command: ./gradlew releaseTar
      - run:
          name: Generate CycloneDX BOM
          command: ./gradlew cyclonedxBom

  oss_analysis:
    steps:
      - checkout
      - run:
          name: Clean BOM file
          command: rm -rf /home/circleci/project/build/reports/bom.xml
      - run:
          name: Generate CycloneDX BOM
          command: ./gradlew cyclonedxBom

  dependency_track_publisher:
    steps:
      - checkout
      - run:
          name: Publish to Dependency Track
          command: |
            dependency-track-publisher \
              --artifact /home/circleci/project/build/reports/bom.xml \
              --projectName FacimateRelease \
              --projectVersion 1.0.1 \
              --apiKey $DEPTRACKER \
              --properties '{"tags": ["tag1"], "swidTagId": "1213", "group": "com.logicfocus"}'

  publish:
    steps:
      - checkout
      - run:
          name: Upload to Nexus
          command: |
            nexusArtifactUploader \
              --artifactId FacimateRelease \
              --file /home/circleci/project/build/distributions/facimate-services-1.0.tar \
              --credentialsId nexus1 \
              --groupId com.logicfocus \
              --nexusUrl http://192.168.1.30:8081 \
              --repository FacimateRelease \
              --version 1.0.1

  build_info:
    environment:
      NEXUS_URL: 'http://192.168.1.30:8081'
      REPO_NAME: 'FR'
      GROUP_ID: 'com.logicfocus'
      ARTIFACT_ID: 'FR'
      VERSION: '1.0.1'
    steps:
      - checkout
      - run:
          name: Generate Build Info
          command: |
            artifactPath="/${REPO_NAME}/${GROUP_ID//./}/${ARTIFACT_ID}/${VERSION}/${ARTIFACT_ID}-${VERSION}.tar"
            nexusChecksumUrl="${NEXUS_URL}/service/rest/v1/components?repository=${REPO_NAME}&group=${GROUP_ID}&name=${ARTIFACT_ID}&version=${VERSION}"
            artifactInfo=$(curl -s -u admin:lfadmin "${nexusChecksumUrl}")
            checksumValue=$(echo "${artifactInfo}" | jq -r '.items[0].assets[0].checksum.sha1')

            echo '{' > buildData.json
            echo '  "buildnumber": "'"${CIRCLE_BUILD_NUM}"'",' >> buildData.json
            echo '  "buildurl": "'"${CIRCLE_BUILD_URL}"'",' >> buildData.json
            echo '  "group": "'"${GROUP_ID}"'",' >> buildData.json
            echo '  "checksum": "'"${checksumValue}"'",' >> buildData.json
            echo '  "artifact": "'"${ARTIFACT_ID}"'",' >> buildData.json
            echo '  "ext": "tar",' >> buildData.json
            echo '  "version": "'"${VERSION}"'"' >> buildData.json
            echo '}' >> buildData.json

  read_build_info:
    steps:
      - checkout
      - run:
          name: Read Build Info
          command: |
            buildData=$(cat buildData.json)
            echo "Build Data: ${buildData}"
            cp buildData.json ~/repo/

  run_cd_pipeline:
    steps:
      - checkout
      - run:
          name: Trigger CD Pipeline
          command: |
            cloudBeesFlowRunPipeline \
              --addParam '{"pipeline":{"pipelineName":"FR","parameters":[]}}' \
              --configuration '/project/Default/pluginConfiguration/jenkins' \
              --pipelineName 'FR' \
              --projectName 'Default' \
              --stageOption 'runAllStages' \
              --stagesToRun '{"pipeline":{"pipelineName":"FR","stages":[{"stageName":"Download Form Nexus Stage ","stageValue":""},{"stageName":"stage2","stageValue":""},{"stageName":"stage3","stageValue":""},{"stageName":"stage4","stageValue":""}]}}' \
              --startingStage ''

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - sonar_analysis:
          requires:
            - build
      - package:
          requires:
            - sonar_analysis
      - oss_analysis:
          requires:
            - package
      - dependency_track_publisher:
          requires:
            - oss_analysis
      - publish:
          requires:
            - dependency_track_publisher
      - build_info:
          requires:
            - publish
      - read_build_info:
          requires:
            - build_info
      - run_cd_pipeline:
          requires:
            - read_build_info

