version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
